apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-name
  name: app-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-name
  template:
    spec:
      containers:
        - image: base-container-image
          imagePullPolicy: Always
          name: app-name
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env: []
