apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- /application/deployment.yaml
- /application/service.yaml
- /tekton/build-java-s2i-pipeline.yaml
- /tekton/promote-pipeline.yaml

images:
- name: app-image-name
  newTag: latest
